[connections.gsheets]
spreadsheet = "https://google.com"
type = "service_account"
project_id = "seu-projeto"
private_key_id = "sua-chave-id"
private_key = "-----BEGIN PRIVATE KEY-----\nSUA_CHAVE_AQUI\n-----END PRIVATE KEY-----\n"
client_email = "seu-email-servico@://gserviceaccount.com"
